import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/globals.css';
import { Locale, i18n } from '@/i18n-config';

const inter = Inter({ subsets: ['latin'] });

/**
 * Generates an array of static parameters for each locale in the i18n configuration.
 * @returns An array of objects with a `lang` property representing each locale.
 */
export async function generateStaticParams() {
  return i18n.locales.map(locale => ({
    lang: locale,
  }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  // console.log('[layout component]', params);

  return (
    <html lang={params.lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
